apiVersion: v1
kind: Service
metadata:
  name: ga-churned-users-service
  labels:
    run: ga-churned-users
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6868
  selector:
    run: ga-churned-users

